// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu4xmkf8kAHfJ2-SMOomagN0ZWZD15CsA',
    appId: '1:930643175597:web:0af4720704e51c1dcdbe24',
    messagingSenderId: '930643175597',
    projectId: 'chat-app-df48a',
    authDomain: 'chat-app-df48a.firebaseapp.com',
    storageBucket: 'chat-app-df48a.appspot.com',
    measurementId: 'G-9K1SPBLGZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARodG-9XNZ5YjV3QhWLPOxPjlsxLeYzis',
    appId: '1:930643175597:android:007b3005ee631849cdbe24',
    messagingSenderId: '930643175597',
    projectId: 'chat-app-df48a',
    storageBucket: 'chat-app-df48a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdMqpMb88OzftIGMmUwv3zT4OHLEHBgWk',
    appId: '1:930643175597:ios:ef413464da984b72cdbe24',
    messagingSenderId: '930643175597',
    projectId: 'chat-app-df48a',
    storageBucket: 'chat-app-df48a.appspot.com',
    iosClientId: '930643175597-mdlolhpllj1r7o0daknfjgd66m5etdld.apps.googleusercontent.com',
    iosBundleId: 'com.example.sent',
  );
}
